# Generated by Django 5.2.12 on 2026-08-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_ID',
            new_name='product_id',
        ),
    ]
